// Centralized tour configurations for all pages

export const alertsTourSteps = [
  {
    target: '[data-tour="alerts-title"]',
    title: 'Security Alerts Dashboard',
    content: 'This is your central hub for managing security alerts generated by MAES analysis. Monitor threats, investigate incidents, and track resolution status.',
    tourId: 'alerts-tour'
  },
  {
    target: '[data-tour="severity-filters"]',
    title: 'Filter by Severity',
    content: 'Use these tabs to filter alerts by severity level: Critical, High, Medium, and Low. This helps prioritize your incident response workflow.',
    tourId: 'alerts-tour'
  },
  {
    target: '[data-tour="alert-actions"]',
    title: 'Bulk Actions',
    content: 'Select multiple alerts to perform bulk actions like marking as read, resolving, or escalating. Efficient management for busy security teams.',
    tourId: 'alerts-tour'
  },
  {
    target: '[data-tour="alerts-table"]',
    title: 'Alerts Table',
    content: 'View detailed information about each alert including severity, category, affected entities, and MITRE ATT&CK techniques. Click on alerts for detailed investigation.',
    tourId: 'alerts-tour'
  },
  {
    target: '[data-tour="create-alert"]',
    title: 'Create Manual Alert',
    content: 'Create custom alerts for manual observations or external threat intelligence. Useful for documenting security events not captured by automated analysis.',
    tourId: 'alerts-tour'
  }
];

export const analysisTourSteps = [
  {
    target: '[data-tour="analysis-title"]',
    title: 'Security Analysis Engine',
    content: 'The Analysis page allows you to run comprehensive security analysis on your Microsoft 365 data. Upload files or analyze extracted data for threats and anomalies.',
    tourId: 'analysis-tour'
  },
  {
    target: '[data-tour="analysis-jobs"]',
    title: 'Analysis Jobs',
    content: 'Monitor running and completed analysis jobs. Each job processes your data through multiple security detection rules and behavioral analysis.',
    tourId: 'analysis-tour'
  },
  {
    target: '[data-tour="upload-files"]',
    title: 'Upload Files',
    content: 'Upload Microsoft 365 audit logs, Exchange data, or other security files for analysis. Supports various formats including JSON, CSV, and XML.',
    tourId: 'analysis-tour'
  },
  {
    target: '[data-tour="analysis-results"]',
    title: 'Analysis Results',
    content: 'View detailed results from completed analysis including detected threats, behavioral anomalies, and MITRE ATT&CK technique mappings.',
    tourId: 'analysis-tour'
  }
];

export const reportsTourSteps = [
  {
    target: '[data-tour="reports-title"]',
    title: 'Security Reports',
    content: 'Generate comprehensive security reports from your analysis results. Create executive summaries, technical reports, and compliance documentation.',
    tourId: 'reports-tour'
  },
  {
    target: '[data-tour="report-templates"]',
    title: 'Report Templates',
    content: 'Choose from pre-built report templates for different audiences: Executive Summary, Technical Analysis, Compliance Report, and Incident Response.',
    tourId: 'reports-tour'
  },
  {
    target: '[data-tour="generate-report"]',
    title: 'Generate Report',
    content: 'Create new reports by selecting data sources, time ranges, and report format. Reports can be exported as PDF, Word, or HTML.',
    tourId: 'reports-tour'
  },
  {
    target: '[data-tour="report-history"]',
    title: 'Report History',
    content: 'Access previously generated reports, download them, or use them as templates for new reports. Track report generation and sharing history.',
    tourId: 'reports-tour'
  }
];

export const settingsTourSteps = [
  {
    target: '[data-tour="settings-title"]',
    title: 'Platform Settings',
    content: 'Configure MAES platform settings including organization details, extraction preferences, analysis rules, and theme preferences.',
    tourId: 'settings-tour'
  },
  {
    target: '[data-tour="settings-tabs"]',
    title: 'Settings Categories',
    content: 'Settings are organized into tabs: General (organization info), Appearance (themes), Extraction (M365 settings), Analysis (detection rules), and Credentials.',
    tourId: 'settings-tour'
  },
  {
    target: '[data-tour="theme-settings"]',
    title: 'Theme & Appearance',
    content: 'Customize the platform appearance with professional themes optimized for security operations. Choose from Dark, Light, Blue, Matrix, and Cyberpunk themes.',
    tourId: 'settings-tour'
  },
  {
    target: '[data-tour="credentials-settings"]',
    title: 'M365 Credentials',
    content: 'Configure Microsoft 365 authentication credentials for data extraction. Supports both client secret and certificate-based authentication.',
    tourId: 'settings-tour'
  }
];

export const getTourStepsById = (tourId) => {
  const tourMap = {
    'alerts-tour': alertsTourSteps,
    'analysis-tour': analysisTourSteps,
    'reports-tour': reportsTourSteps,
    'settings-tour': settingsTourSteps
  };
  return tourMap[tourId] || [];
};